In [1]:
import torch

print(torch.__version__)

2.9.1+cu128


In [2]:
print(torch.cuda.is_available())

True


In [3]:
tensor0d = torch.tensor(1)

tensor1d = torch.tensor([1, 2, 3])

tensor2d = torch.tensor([[1, 2, 3], [4, 5, 6]])

tensor3d = torch.tensor([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(tensor0d)
print(tensor1d)
print(tensor2d)
print(tensor3d)


tensor(1)
tensor([1, 2, 3])
tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]])


In [4]:
tensor1d = torch.tensor([1, 2, 3])
print(tensor1d.dtype)

torch.int64


In [5]:
floatvec = torch.tensor([1.0, 2.0, 3.0])
print(floatvec.dtype)

torch.float32


In [6]:
floatvec = tensor1d.to(torch.float32)
print(floatvec.dtype)

torch.float32


## A.2.3

In [7]:
tensor2d = torch.tensor([[1, 2, 3], [4, 5, 6]])
print(tensor2d)

tensor([[1, 2, 3],
        [4, 5, 6]])


In [8]:
print(tensor2d.shape)

torch.Size([2, 3])


In [9]:
print(tensor2d.reshape(3,2))

tensor([[1, 2],
        [3, 4],
        [5, 6]])


In [10]:
print(tensor2d.view(3,2))

tensor([[1, 2],
        [3, 4],
        [5, 6]])


In [12]:
print(tensor2d)

tensor([[1, 2, 3],
        [4, 5, 6]])


In [13]:
print(tensor2d.T)

tensor([[1, 4],
        [2, 5],
        [3, 6]])


In [14]:
print(tensor2d.matmul(tensor2d.T))

tensor([[14, 32],
        [32, 77]])


In [15]:
print(tensor2d @ tensor2d.T)

tensor([[14, 32],
        [32, 77]])


In [18]:
import torch.nn.functional as F

y = torch.tensor([1.0])
x1 = torch.tensor([1.1])
w1 = torch.tensor([2.2])
b = torch.tensor([0.0])

z = x1 * w1 + b
a = torch.sigmoid(z)

loss = F.binary_cross_entropy(a, y)

print(z)
print(a)
print(loss)

tensor([2.4200])
tensor([0.9183])
tensor(0.0852)


In [19]:
import torch.nn.functional as F
from torch.autograd import grad

y = torch.tensor([1.0])
x1 = torch.tensor([1.1])
w1 = torch.tensor([2.2], requires_grad=True)
b = torch.tensor([0.0], requires_grad=True)

z = x1 * w1 + b
a = torch.sigmoid(z)

loss = F.binary_cross_entropy(a, y)

print(z)
print(a)
print(loss)

grad_L_w1 = grad(loss, w1, retain_graph=True)
grad_L_b = grad(loss, b, retain_graph=True)

print(grad_L_w1)
print(grad_L_b)

tensor([2.4200], grad_fn=<AddBackward0>)
tensor([0.9183], grad_fn=<SigmoidBackward0>)
tensor(0.0852, grad_fn=<BinaryCrossEntropyBackward0>)
(tensor([-0.0898]),)
(tensor([-0.0817]),)


In [20]:
loss.backward()
print(w1.grad)
print(b.grad)

tensor([-0.0898])
tensor([-0.0817])


In [31]:
class NuralNetwork(torch.nn.Module):
    def __init__(self, num_inputs, num_outputs):
        super().__init__()

        self.layers = torch.nn.Sequential(
            # 1つ目の隠れ層
            torch.nn.Linear(num_inputs, 30),
            torch.nn.ReLU(),

            # 2つ目の隠れ層
            torch.nn.Linear(30, 20),
            torch.nn.ReLU(),

            # 出力層
            torch.nn.Linear(20, num_outputs)
        )

    def forward(self, x):
        logits = self.layers(x)
        return logits


In [32]:
model = NuralNetwork(50, 3)

In [33]:
print(model)

NuralNetwork(
  (layers): Sequential(
    (0): Linear(in_features=50, out_features=30, bias=True)
    (1): ReLU()
    (2): Linear(in_features=30, out_features=20, bias=True)
    (3): ReLU()
    (4): Linear(in_features=20, out_features=3, bias=True)
  )
)


In [34]:
num_params = sum(p.numel() for p in model.parameters() if p.requires_grad)
print("Total number of trainable parameters:", num_params)

Total number of trainable parameters: 2213


In [36]:
print(model.layers[0].weight)

Parameter containing:
tensor([[-0.0276,  0.0962,  0.1289,  ...,  0.0084, -0.0758,  0.0605],
        [-0.0653, -0.0055, -0.1084,  ..., -0.0335,  0.0914,  0.0835],
        [ 0.0432, -0.0327,  0.0529,  ..., -0.0939,  0.0639,  0.0906],
        ...,
        [-0.0167, -0.0102, -0.0972,  ...,  0.0231, -0.0910, -0.0120],
        [-0.1162,  0.0252, -0.0483,  ..., -0.0629, -0.0735,  0.1098],
        [-0.0732,  0.0823, -0.1412,  ..., -0.0342,  0.0703,  0.0630]],
       requires_grad=True)


In [37]:
print(model.layers[0].weight.shape)

torch.Size([30, 50])


In [38]:
torch.manual_seed(123)
model = NuralNetwork(50, 3)
print(model.layers[0].weight)

Parameter containing:
tensor([[-0.0577,  0.0047, -0.0702,  ...,  0.0222,  0.1260,  0.0865],
        [ 0.0502,  0.0307,  0.0333,  ...,  0.0951,  0.1134, -0.0297],
        [ 0.1077, -0.1108,  0.0122,  ...,  0.0108, -0.1049, -0.1063],
        ...,
        [-0.0787,  0.1259,  0.0803,  ...,  0.1218,  0.1303, -0.1351],
        [ 0.1359,  0.0175, -0.0673,  ...,  0.0674,  0.0676,  0.1058],
        [ 0.0790,  0.1343, -0.0293,  ...,  0.0344, -0.0971, -0.0509]],
       requires_grad=True)


In [39]:
torch.manual_seed(123)
x = torch.rand((1, 50))
out = model(x)
print(out)

tensor([[-0.1262,  0.1080, -0.1792]], grad_fn=<AddmmBackward0>)


In [40]:
with torch.no_grad():
    out = model(x)
print(out)

tensor([[-0.1262,  0.1080, -0.1792]])


In [41]:
with torch.no_grad():
    out = torch.softmax(model(x), dim=1)
print(out)

tensor([[0.3113, 0.3934, 0.2952]])


## A.6