In [51]:
import torch

from ch05.ch05 import num_epochs

print(torch.__version__)

2.9.1+cu128


In [52]:
print(torch.cuda.is_available())

True


In [53]:
tensor0d = torch.tensor(1)

tensor1d = torch.tensor([1, 2, 3])

tensor2d = torch.tensor([[1, 2, 3], [4, 5, 6]])

tensor3d = torch.tensor([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(tensor0d)
print(tensor1d)
print(tensor2d)
print(tensor3d)


tensor(1)
tensor([1, 2, 3])
tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]])


In [54]:
tensor1d = torch.tensor([1, 2, 3])
print(tensor1d.dtype)

torch.int64


In [55]:
floatvec = torch.tensor([1.0, 2.0, 3.0])
print(floatvec.dtype)

torch.float32


In [56]:
floatvec = tensor1d.to(torch.float32)
print(floatvec.dtype)

torch.float32


## A.2.3

In [57]:
tensor2d = torch.tensor([[1, 2, 3], [4, 5, 6]])
print(tensor2d)

tensor([[1, 2, 3],
        [4, 5, 6]])


In [58]:
print(tensor2d.shape)

torch.Size([2, 3])


In [59]:
print(tensor2d.reshape(3,2))

tensor([[1, 2],
        [3, 4],
        [5, 6]])


In [60]:
print(tensor2d.view(3,2))

tensor([[1, 2],
        [3, 4],
        [5, 6]])


In [61]:
print(tensor2d)

tensor([[1, 2, 3],
        [4, 5, 6]])


In [62]:
print(tensor2d.T)

tensor([[1, 4],
        [2, 5],
        [3, 6]])


In [63]:
print(tensor2d.matmul(tensor2d.T))

tensor([[14, 32],
        [32, 77]])


In [64]:
print(tensor2d @ tensor2d.T)

tensor([[14, 32],
        [32, 77]])


In [65]:
import torch.nn.functional as F

y = torch.tensor([1.0])
x1 = torch.tensor([1.1])
w1 = torch.tensor([2.2])
b = torch.tensor([0.0])

z = x1 * w1 + b
a = torch.sigmoid(z)

loss = F.binary_cross_entropy(a, y)

print(z)
print(a)
print(loss)

tensor([2.4200])
tensor([0.9183])
tensor(0.0852)


In [66]:
import torch.nn.functional as F
from torch.autograd import grad

y = torch.tensor([1.0])
x1 = torch.tensor([1.1])
w1 = torch.tensor([2.2], requires_grad=True)
b = torch.tensor([0.0], requires_grad=True)

z = x1 * w1 + b
a = torch.sigmoid(z)

loss = F.binary_cross_entropy(a, y)

print(z)
print(a)
print(loss)

grad_L_w1 = grad(loss, w1, retain_graph=True)
grad_L_b = grad(loss, b, retain_graph=True)

print(grad_L_w1)
print(grad_L_b)

tensor([2.4200], grad_fn=<AddBackward0>)
tensor([0.9183], grad_fn=<SigmoidBackward0>)
tensor(0.0852, grad_fn=<BinaryCrossEntropyBackward0>)
(tensor([-0.0898]),)
(tensor([-0.0817]),)


In [67]:
loss.backward()
print(w1.grad)
print(b.grad)

tensor([-0.0898])
tensor([-0.0817])


In [68]:
class NuralNetwork(torch.nn.Module):
    def __init__(self, num_inputs, num_outputs):
        super().__init__()

        self.layers = torch.nn.Sequential(
            # 1つ目の隠れ層
            torch.nn.Linear(num_inputs, 30),
            torch.nn.ReLU(),

            # 2つ目の隠れ層
            torch.nn.Linear(30, 20),
            torch.nn.ReLU(),

            # 出力層
            torch.nn.Linear(20, num_outputs)
        )

    def forward(self, x):
        logits = self.layers(x)
        return logits


In [69]:
model = NuralNetwork(50, 3)

In [70]:
print(model)

NuralNetwork(
  (layers): Sequential(
    (0): Linear(in_features=50, out_features=30, bias=True)
    (1): ReLU()
    (2): Linear(in_features=30, out_features=20, bias=True)
    (3): ReLU()
    (4): Linear(in_features=20, out_features=3, bias=True)
  )
)


In [71]:
num_params = sum(p.numel() for p in model.parameters() if p.requires_grad)
print("Total number of trainable parameters:", num_params)

Total number of trainable parameters: 2213


In [72]:
print(model.layers[0].weight)

Parameter containing:
tensor([[ 0.0223,  0.1169, -0.1336,  ...,  0.1287,  0.0700, -0.0006],
        [ 0.1004, -0.0725,  0.0729,  ...,  0.0119, -0.1257,  0.0811],
        [ 0.0295,  0.1368, -0.1006,  ...,  0.0029, -0.0206,  0.0908],
        ...,
        [-0.0373, -0.0827,  0.0705,  ...,  0.1352,  0.1175,  0.0521],
        [ 0.1233,  0.0023,  0.0692,  ...,  0.0924, -0.1412, -0.1232],
        [-0.1063,  0.0081, -0.1249,  ...,  0.0912,  0.0984,  0.0735]],
       requires_grad=True)


In [73]:
print(model.layers[0].weight.shape)

torch.Size([30, 50])


In [74]:
torch.manual_seed(123)
model = NuralNetwork(50, 3)
print(model.layers[0].weight)

Parameter containing:
tensor([[-0.0577,  0.0047, -0.0702,  ...,  0.0222,  0.1260,  0.0865],
        [ 0.0502,  0.0307,  0.0333,  ...,  0.0951,  0.1134, -0.0297],
        [ 0.1077, -0.1108,  0.0122,  ...,  0.0108, -0.1049, -0.1063],
        ...,
        [-0.0787,  0.1259,  0.0803,  ...,  0.1218,  0.1303, -0.1351],
        [ 0.1359,  0.0175, -0.0673,  ...,  0.0674,  0.0676,  0.1058],
        [ 0.0790,  0.1343, -0.0293,  ...,  0.0344, -0.0971, -0.0509]],
       requires_grad=True)


In [75]:
torch.manual_seed(123)
x = torch.rand((1, 50))
out = model(x)
print(out)

tensor([[-0.1262,  0.1080, -0.1792]], grad_fn=<AddmmBackward0>)


In [76]:
with torch.no_grad():
    out = model(x)
print(out)

tensor([[-0.1262,  0.1080, -0.1792]])


In [77]:
with torch.no_grad():
    out = torch.softmax(model(x), dim=1)
print(out)

tensor([[0.3113, 0.3934, 0.2952]])


## A.6

In [78]:
x_train = torch.tensor([
    [-1.2, 3.1],
    [-0.9, 2.9],
    [-0.5, 2.6],
    [2.3, -1.1],
    [2.7, -1.5]
])
y_train = torch.tensor([0, 0, 0, 1, 1])

x_test = torch.tensor([
    [-0.8, 2.8],
    [2.6, -1.6],
])

y_test = torch.tensor([0, 1])

In [79]:
from torch.utils.data import Dataset

class ToyDataset(Dataset):
    def __init__(self, X, y):
        self.features = X
        self.labels = y

    def __getitem__(self, index):
        one_x = self.features[index]
        one_y = self.labels[index]
        return one_x, one_y

    def __len__(self):
        return self.labels.shape[0]

train_ds = ToyDataset(x_train, y_train)
test_ds = ToyDataset(x_test, y_test)


In [80]:
print(len(train_ds))

5


In [81]:
from torch.utils.data import DataLoader

torch.manual_seed(123)

train_loader = DataLoader(
    dataset=train_ds,
    batch_size=2,
    shuffle=True,
    num_workers=0
)

test_loader = DataLoader(
    dataset=test_ds,
    batch_size=2,
    shuffle=False,
    num_workers=0
)


In [82]:
for idx, (x, y) in enumerate(train_loader):
    print(f"Batch {idx+1}:", x, y)


Batch 1: tensor([[ 2.3000, -1.1000],
        [-0.9000,  2.9000]]) tensor([1, 0])
Batch 2: tensor([[-1.2000,  3.1000],
        [-0.5000,  2.6000]]) tensor([0, 0])
Batch 3: tensor([[ 2.7000, -1.5000]]) tensor([1])


In [83]:
train_loader = DataLoader(
    dataset=train_ds,
    batch_size=2,
    shuffle=True,
    num_workers=0,
    drop_last=True
)

In [84]:
for idx, (x, y) in enumerate(train_loader):
    print(f"Batch {idx+1}:", x, y)

Batch 1: tensor([[-1.2000,  3.1000],
        [-0.5000,  2.6000]]) tensor([0, 0])
Batch 2: tensor([[ 2.3000, -1.1000],
        [-0.9000,  2.9000]]) tensor([1, 0])


## A.7

In [86]:
import torch.nn.functional as F

torch.manual_seed(123)
model = NuralNetwork(num_inputs=2, num_outputs=2)
optimizer = torch.optim.SGD(model.parameters(), lr=0.5)

num_epochs = 3

for epoch in range(num_epochs):
    model.train()

    for batch_idx, (features, labels) in enumerate(train_loader):
        logits = model(features)
        loss = F.cross_entropy(logits, labels)

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        ### Logging
        print(f"Epoch {epoch+1:03d}/{num_epochs:03d} | Batch {batch_idx:03d}/{len(train_loader):03d} | Train Loss: {loss:.2f}")

    model.eval()


Epoch 001/003 | Batch 000/002 | Train Loss: 0.75
Epoch 001/003 | Batch 001/002 | Train Loss: 0.65
Epoch 002/003 | Batch 000/002 | Train Loss: 0.44
Epoch 002/003 | Batch 001/002 | Train Loss: 0.13
Epoch 003/003 | Batch 000/002 | Train Loss: 0.03
Epoch 003/003 | Batch 001/002 | Train Loss: 0.00


In [88]:
model.eval()
with torch.no_grad():
    outputs = model(x_train)
print(outputs)

tensor([[ 2.8569, -4.1618],
        [ 2.5382, -3.7548],
        [ 2.0944, -3.1820],
        [-1.4814,  1.4816],
        [-1.7176,  1.7342]])


In [89]:
torch.set_printoptions(sci_mode=False)
probas = torch.softmax(outputs, dim=1)
print(probas)

tensor([[0.9991, 0.0009],
        [0.9982, 0.0018],
        [0.9949, 0.0051],
        [0.0491, 0.9509],
        [0.0307, 0.9693]])


In [90]:
predictions = torch.argmax(probas, dim=1)
print(predictions)

tensor([0, 0, 0, 1, 1])


In [91]:
predictions = torch.argmax(outputs, dim=1)
print(predictions)

tensor([0, 0, 0, 1, 1])


In [92]:
predictions == y_train

tensor([True, True, True, True, True])

In [93]:
torch.sum(predictions == y_train)

tensor(5)

In [94]:
def compute_accuracy(model, dataloader):
    model = model.eval()
    correct = 0.0
    total_examples = 0

    for idx, (features, labels) in enumerate(dataloader):
        with torch.no_grad():
            logits = model(features)

        predictions = torch.argmax(logits, dim=1)
        compare = predictions == labels
        correct += torch.sum(compare)
        total_examples += len(compare)

    return (correct / total_examples).item()

In [95]:
print(compute_accuracy(model, train_loader))

1.0


In [96]:
print(compute_accuracy(model, test_loader))

1.0


## A.8

In [97]:
torch.save(model.state_dict(), "model.pth")


In [98]:
model = NuralNetwork(2,2)
model.load_state_dict(torch.load("model.pth"))

<All keys matched successfully>

In [99]:
print(torch.cuda.is_available())

True


In [100]:
tensor_1 = torch.tensor([1.,2.,3.])
tensor_2 = torch.tensor([4.,5.,6.])
print(tensor_1 + tensor_2)

tensor([5., 7., 9.])


In [101]:
tensor_1 = tensor_1.to("cuda")
tensor_2 = tensor_2.to("cuda")
print(tensor_1 + tensor_2)

tensor([5., 7., 9.], device='cuda:0')


In [103]:
# tensor_1 = tensor_1.to("cpu")
# tensor_2 = tensor_2.to("cuda")
# print(tensor_1 + tensor_2)

In [104]:
torch.manual_seed(123)

model = NuralNetwork(num_inputs=2,num_outputs=2)

device = torch.device("cuda")
model = model.to(device)

optimizer = torch.optim.SGD(model.parameters(), lr=0.5)

num_epochs = 3

for epoch in range(num_epochs):

    model.train()

    for batch_idx, (features, labels) in enumerate(train_loader):
        features = features.to(device)
        labels = labels.to(device)

        logits = model(features)
        loss = F.cross_entropy(logits, labels)

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        ### Logging
        print(f"Epoch {epoch+1:03d}/{num_epochs:03d} | Batch {batch_idx+1:03d}/{len(train_loader):03d} | Train Loss: {loss:.2f}")

    model.eval()

Epoch 001/003 | Batch 001/002 | Train Loss: 0.75
Epoch 001/003 | Batch 002/002 | Train Loss: 0.65
Epoch 002/003 | Batch 001/002 | Train Loss: 0.44
Epoch 002/003 | Batch 002/002 | Train Loss: 0.13
Epoch 003/003 | Batch 001/002 | Train Loss: 0.03
Epoch 003/003 | Batch 002/002 | Train Loss: 0.00


In [106]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")